### ISSUE TITLE
[HTTP Error] Is there a maximum amout of translations?

### ISSUE THREAD

**Issue by Marki396** [iamtraction/google-translate#29]
After some translations in a for loop i get an error [HTTP Error].
Is there a maximum amount of translations available  for a specific amount of time?

`const translate = require('@iamtraction/google-translate');`

`for (const keywordToTranslate of keyWordsList) {
			await translate(keywordToTranslate, { from: 'de', to: 'en' }).then(res => {
				keyWordsListEN.push(res.text);
			}).catch(err => {
				console.error(err);
			});
		}`

**Comment by yadavamarjeet** [comment]
according to https://support.google.com/translate/thread/3870393?hl=en "The translate.googleapis.com site use is very limited. It only allows about 100 requests per one hour period and there after returns a 429 error (Too many requests).  On the other hand, the Google Translate Api has a default billable limit of 5 requests/second/user and 200,000 requests/day."

The Google Translate API has a specific Google Group where many more people discuss that product since we don't get too many questions about the API so you may find https://groups.google.com/forum/#!forum/google-translate-api very interesting to read.

Google Translate API does come with their own support located at https://cloud.google.com/support-hub/ as well since Google Cloud Platform can cost money (the API is something that can incur costs).

**Comment by taishi55** [comment]
Can you avoid to hit the limit by changing ip address?

**Comment by iamtraction** [comment]
yes, you can.

**Comment by taishi55** [comment]
May I ask how to do it??

I already hit the limt and getting the following error.
```
SyntaxError: Unexpected token < in JSON at position 0
at JSON.parse (<anonymous>)
at node_modules/undici/lib/api/readable.js:237:20)
```

**Comment by iamtraction** [comment]
you've to use a proxy/vpn. or wait for the rate limit to expire.

**Comment by taishi55** [comment]
Yes I'm trying to integrate `http-proxy-agent`. I wonder if your module is cabpable for it

**Comment by iamtraction** [comment]
try it out and let me know. i have not tested it.

**Comment by taishi55** [comment]
I'm not so familiar with proxy... 

I found [this google translate library](https://github.com/cjvnjde/google-translate-api-browser). So far I looped so many time, but I don't get any limiations. You want to check this out!!
